/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AccountSelect: typeof import('./src/components/wallet/AccountSelect.vue')['default']
    Avatar: typeof import('./src/components/common/Avatar.vue')['default']
    BotFiProvider: typeof import('./src/layouts/BotFiProvider.vue')['default']
    ChainSelect: typeof import('./src/components/wallet/ChainSelect.vue')['default']
    DefaultNetworkAndWallet: typeof import('./src/components/modals/default-network-and-wallet.vue')['default']
    Icon: typeof import('./src/components/common/Icon.vue')['default']
    Image: typeof import('./src/components/common/Image.vue')['default']
    LoadingView: typeof import('./src/layouts/LoadingView.vue')['default']
    MainBtn: typeof import('./src/components/common/MainBtn.vue')['default']
    MainLayout: typeof import('./src/layouts/MainLayout.vue')['default']
    Modal: typeof import('./src/components/modals/modal.vue')['default']
    ModalSelect: typeof import('./src/components/modals/modal-select.vue')['default']
    NativeBackBtn: typeof import('./src/components/common/NativeBackBtn.vue')['default']
    Nav: typeof import('./src/components/header/Nav.vue')['default']
    Navbar: typeof import('./src/components/header/Navbar.vue')['default']
    NetAndAccountSelect: typeof import('./src/components/modals/NetAndAccountSelect.vue')['default']
    NetworkAndAccount: typeof import('./src/components/modals/NetworkAndAccount.vue')['default']
    NetworkSelect: typeof import('./src/components/modals/network-select.vue')['default']
    Pin: typeof import('./src/components/common/Pin.vue')['default']
    Pincode: typeof import('./src/components/common/Pincode.vue')['default']
    PinCode: typeof import('./src/components/common/PinCode.vue')['default']
    ProfilePhoto: typeof import('./src/components/common/ProfilePhoto.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchForm: typeof import('./src/components/common/SearchForm.vue')['default']
    SidePanel: typeof import('./src/components/wallet/SidePanel.vue')['default']
    TabBar: typeof import('./src/components/wallet/TabBar.vue')['default']
    Toast: typeof import('./src/components/common/Toast.vue')['default']
    TokenIcon: typeof import('./src/components/common/TokenIcon.vue')['default']
    TopBackBtn: typeof import('./src/components/header/TopBackBtn.vue')['default']
    TopLogo: typeof import('./src/components/header/TopLogo.vue')['default']
    ValidPasswordHints: typeof import('./src/components/common/ValidPasswordHints.vue')['default']
    WalletLayout: typeof import('./src/layouts/WalletLayout.vue')['default']
  }
}
