export default {
    RPC_CONNECT_FAILED:         100,
    WALLET_NOT_CONNECTED:       101,
    WALLET_DECRYPTION_ERROR:    102,
    PASSWORD_REQUIRED:          103,
    DEFAULT_WALLET_NOT_FOUND:   104,
    WALLET_IMPORT_BY_PK_FAILED: 105
}